services:
  go_external_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_external_service
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: config/config.yaml